controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    jackal_controller:
      type: diff_drive_controller/DiffDriveController

    # Controller names
jackal_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["wheel_front_left_joint", "wheel_back_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_back_right_joint"]
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25
    publish_cmd: true
    k_l: 0.1
    k_r: 0.1
    wheel_separation: 0.37559
    wheel_radius: 0.098
    base_frame_id: base_link

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0  # m/s
        min_velocity: -2.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 20.0  # m/s^2
        min_acceleration: -20.0  # m/s^2

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 25.0  # rad/s^2
